import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useStore from '../zustand/store'
import UserData from '../components/UserData'
import Input from '../components/Input'

export default function Home() {
  const user = useStore(state =>  state.user)

  return (
    <div className={styles.container}>
      <Head>
        <title>LitWiz Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>People</h1>
      <Input/>
      <hr/>
      <UserData/>
      <hr/>
     
      {/* <StoreC/> */}
    </div>
  )
}
